#!/usr/bin/env python3
"""
Stage 3: supervised attack-identification classifier.

This is an ORDINARY supervised classifier (Random Forest). It is NOT the
reinforcement-learning part of the project -- it has no notion of "campaign"
or "correlation," it just labels one flow at a time. Its output (predicted
attack_type per event) becomes part of the STATE representation the Stage-4
DQN correlator will read; the two stages are deliberately kept independent.

Two leakage risks were identified and are handled explicitly here, not as an
afterthought:

1. IP/port shortcut leakage: every attack type in CICIDS2017 was generated by
   the same fixed attacker VM (172.16.0.1) against the same fixed victim
   (192.168.10.50), while benign traffic involves thousands of distinct real
   IPs and never includes 172.16.0.1. Any model given src_ip/dst_ip as a
   feature would trivially hit ~100% by keying on that address rather than
   learning genuine flow-based attack signatures. These columns are dropped
   -- see src/schema.py:CICIDS_LEAKAGE_COLUMNS for the full list and the
   verification that motivated it.

2. Burst/near-duplicate leakage: floods (DoS Hulk, port scans, DDoS) produce
   tens of thousands of near-identical consecutive flow rows. A random
   row-level train/test split would put near-duplicates of the same burst on
   both sides, making the task look artificially easy. Instead, each source
   file is split CHRONOLOGICALLY (first 70% of its timestamps -> train, last
   30% -> test), so train and test never share the same moment of the same
   burst. This is a different, simpler split than Stage 2's campaign-level
   split (which exists for Stage 4/5 DQN tuning) -- keep the two separate
   when writing up results.

Usage:
    python scripts/stage3_train_identifier.py [data/raw/cicids2017/CSVs] [data/processed/stage3]
"""
import sys
import gc
import json
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, f1_score
from sklearn.preprocessing import LabelEncoder
import joblib

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from src.schema import CICIDS_FILE_TO_DAY, CICIDS_LEAKAGE_COLUMNS, PROPOSAL_HEADLINE_CLASSES

ATTACK_FILES = [f for f in CICIDS_FILE_TO_DAY if "benign" not in f]
BENIGN_FILES = [f for f in CICIDS_FILE_TO_DAY if "benign" in f]

# This VM has 2 cores / 3.8GB RAM. The first attempt at this script (float64
# throughout, 260k benign target) was killed by the kernel OOM-killer partway
# through -- confirmed via `journalctl -k` showing an explicit oom-kill of
# this process, not a silent hang. That is why every numeric column is
# downcast to float32 immediately on load below, and why the benign sample
# target is smaller than an unconstrained machine would need.
BENIGN_TOTAL_TARGET = 100_000
RNG_SEED = 42
TRAIN_FRACTION = 0.7            # chronological, per source file
NEAR_PERFECT_F1_THRESHOLD = 0.98


def load_full(path):
    df = pd.read_csv(path)
    df["timestamp"] = pd.to_datetime(df["timestamp"], format="mixed")
    float_cols = df.select_dtypes(include=["float64"]).columns
    df[float_cols] = df[float_cols].astype(np.float32)
    int_cols = df.select_dtypes(include=["int64"]).columns
    for c in int_cols:
        if c not in ("src_port", "dst_port"):  # keep as-is, tiny column anyway
            df[c] = pd.to_numeric(df[c], downcast="integer")
    return df


def chronological_split(df, source_file_col="source_file", train_fraction=TRAIN_FRACTION):
    train_parts, test_parts = [], []
    for _, g in df.groupby(source_file_col):
        g = g.sort_values("timestamp")
        cut = int(len(g) * train_fraction)
        train_parts.append(g.iloc[:cut])
        test_parts.append(g.iloc[cut:])
    return pd.concat(train_parts, ignore_index=True), pd.concat(test_parts, ignore_index=True)


def main():
    raw_root = Path(sys.argv[1] if len(sys.argv) > 1 else "data/raw/cicids2017/CSVs")
    out_root = Path(sys.argv[2] if len(sys.argv) > 2 else "data/processed/stage3")
    out_root.mkdir(parents=True, exist_ok=True)

    # --- load attack rows (all of them; total is manageable) ---
    attack_frames = []
    for fname in ATTACK_FILES:
        path = raw_root / fname
        if not path.exists():
            print(f"WARNING: {path} missing, skipping", flush=True)
            continue
        df = load_full(path)
        df["source_file"] = fname
        attack_frames.append(df)
        print(f"  loaded {fname}: {len(df)} rows", flush=True)
    attacks = pd.concat(attack_frames, ignore_index=True)
    del attack_frames
    gc.collect()
    print(f"Loaded {len(attacks)} attack rows total.", flush=True)

    # --- load benign rows, subsampled per file (proportional, fixed seed) ---
    benign_frames = []
    raw_benign_counts = {}
    for fname in BENIGN_FILES:
        path = raw_root / fname
        if not path.exists():
            continue
        n_lines = sum(1 for _ in open(path)) - 1
        raw_benign_counts[fname] = n_lines
    total_available = sum(raw_benign_counts.values())

    for fname, n_avail in raw_benign_counts.items():
        path = raw_root / fname
        share = n_avail / total_available
        n_sample = max(1000, int(BENIGN_TOTAL_TARGET * share))
        # read full, sample, then immediately discard the full-size frame (files fit
        # individually in RAM even though all five together would not)
        df_full = load_full(path)
        df = df_full.sample(n=min(n_sample, len(df_full)), random_state=RNG_SEED).copy()
        del df_full
        gc.collect()
        df["source_file"] = fname
        benign_frames.append(df)
        print(f"  sampled {len(df)} / {n_avail} benign rows from {fname}", flush=True)

    benign = pd.concat(benign_frames, ignore_index=True)
    del benign_frames
    gc.collect()
    print(f"Sampled {len(benign)} benign rows total (target was {BENIGN_TOTAL_TARGET}).", flush=True)

    combined = pd.concat([attacks, benign], ignore_index=True)
    del attacks, benign
    gc.collect()
    print(f"\nCombined dataset: {len(combined)} rows, {combined['label'].nunique()} classes.", flush=True)
    print(combined["label"].value_counts().to_string(), flush=True)

    # --- chronological per-file split (see module docstring for why) ---
    train_df, test_df = chronological_split(combined)
    del combined
    gc.collect()
    print(f"\nChronological per-file split: {len(train_df)} train / {len(test_df)} test rows.", flush=True)

    # --- feature matrix: drop leakage columns, encode protocol categorically ---
    drop_cols = set(CICIDS_LEAKAGE_COLUMNS) | {"source_file", "day"}
    feature_cols = [c for c in train_df.columns if c not in drop_cols]
    print(f"\nUsing {len(feature_cols)} feature columns (dropped: {sorted(drop_cols & set(train_df.columns))})")

    protocol_encoder = LabelEncoder()
    all_protocols = pd.concat([train_df["protocol"], test_df["protocol"]]).astype(str)
    protocol_encoder.fit(all_protocols)

    numeric_feature_cols = [c for c in feature_cols if c != "protocol"]

    def build_X(df):
        X = df[numeric_feature_cols].astype(np.float32)  # astype already copies, no separate .copy() needed
        X["protocol"] = protocol_encoder.transform(df["protocol"].astype(str)).astype(np.float32)
        return X.replace([np.inf, -np.inf], np.nan).fillna(0)

    X_train, X_test = build_X(train_df), build_X(test_df)
    y_train, y_test = train_df["label"].values, test_df["label"].values
    del train_df, test_df
    gc.collect()
    print(f"Feature matrix ready: X_train={X_train.shape}, X_test={X_test.shape}", flush=True)

    # --- train ---
    print("\nTraining RandomForestClassifier (class_weight='balanced')...", flush=True)
    clf = RandomForestClassifier(
        n_estimators=150,
        max_depth=20,
        min_samples_leaf=3,
        class_weight="balanced",
        n_jobs=2,
        random_state=RNG_SEED,
    )
    clf.fit(X_train, y_train)

    # --- evaluate ---
    y_pred = clf.predict(X_test)
    report = classification_report(y_test, y_pred, output_dict=True, zero_division=0)
    report_text = classification_report(y_test, y_pred, zero_division=0)
    print("\n" + "=" * 70)
    print("Full extended multi-class report (all CICIDS2017 attack types + benign)")
    print("=" * 70)
    print(report_text)

    labels_sorted = sorted(set(y_test) | set(y_pred))
    cm = confusion_matrix(y_test, y_pred, labels=labels_sorted)
    cm_df = pd.DataFrame(cm, index=labels_sorted, columns=labels_sorted)
    cm_df.to_csv(out_root / "confusion_matrix_full.csv")

    # --- train-set support, so we know which classes had enough data to mean anything ---
    train_support = pd.Series(y_train).value_counts()
    test_support = pd.Series(y_test).value_counts()

    print("\n" + "=" * 70)
    print("Per-class support (train / test row counts) -- read F1 alongside this")
    print("=" * 70)
    support_table = pd.DataFrame({"train_n": train_support, "test_n": test_support}).fillna(0).astype(int)
    print(support_table.to_string())

    # --- investigate any near-perfect class, exactly as instructed ---
    print("\n" + "=" * 70)
    print("Near-perfect-score investigation (threshold: F1 >= {:.2f})".format(NEAR_PERFECT_F1_THRESHOLD))
    print("=" * 70)
    flagged = []
    for cls, metrics in report.items():
        if cls in ("accuracy", "macro avg", "weighted avg"):
            continue
        if metrics["f1-score"] >= NEAR_PERFECT_F1_THRESHOLD:
            test_n = int(test_support.get(cls, 0))
            flagged.append((cls, metrics["f1-score"], test_n))

    if not flagged:
        print("No class reached the near-perfect threshold. No investigation needed.")
    else:
        for cls, f1, test_n in flagged:
            if test_n < 15:
                verdict = (f"LOW STATISTICAL POWER, not leakage: test set has only {test_n} "
                           f"examples of this class -- an F1 this high is not meaningful evidence "
                           f"of a well-learned decision boundary, it just means the few test "
                           f"examples happened to be classified correctly. Report this class's "
                           f"score with an explicit small-sample caveat, do not present it as a "
                           f"strong result.")
            else:
                verdict = (f"test set has {test_n} examples (not tiny) -- this needs a real look: "
                           f"check feature importances for this class and confirm the signal is a "
                           f"genuine flow-statistic pattern (e.g. FTP-Patator's very characteristic "
                           f"port/flag pattern) and not a residual leakage path.")
            print(f"  - {cls}: F1={f1:.4f}, test_n={test_n} -> {verdict}")

    # --- headline subset matching the literal proposal taxonomy ---
    print("\n" + "=" * 70)
    print("Headline subset: SQLi / XSS / scan / benign (as literally scoped in the proposal)")
    print("=" * 70)
    for cls in PROPOSAL_HEADLINE_CLASSES:
        if cls in report:
            m = report[cls]
            test_n = int(test_support.get(cls, 0))
            caveat = "  <-- test_n too small to trust this number" if test_n < 15 else ""
            print(f"  {cls:20s} precision={m['precision']:.3f} recall={m['recall']:.3f} "
                  f"f1={m['f1-score']:.3f} test_n={test_n}{caveat}")
        else:
            print(f"  {cls:20s} NOT PRESENT in test split")

    # --- feature importances (top 15), for defending "what did the model actually learn" ---
    importances = pd.Series(clf.feature_importances_, index=X_train.columns).sort_values(ascending=False)
    print("\n" + "=" * 70)
    print("Top 15 feature importances")
    print("=" * 70)
    print(importances.head(15).to_string())

    # --- save everything ---
    joblib.dump(clf, out_root / "random_forest_identifier.joblib")
    joblib.dump(protocol_encoder, out_root / "protocol_encoder.joblib")
    with open(out_root / "classification_report_full.json", "w") as f:
        json.dump(report, f, indent=2)
    with open(out_root / "classification_report_full.txt", "w") as f:
        f.write(report_text)
    importances.to_csv(out_root / "feature_importances.csv")
    support_table.to_csv(out_root / "per_class_support.csv")

    print(f"\nSaved model, reports, confusion matrix, and feature importances to {out_root}/")


if __name__ == "__main__":
    main()
